version: '3.4'

services:
  
  taskplanner_db:
    environment:
      SA_PASSWORD: "@sqlserver2023"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 

  taskplanner:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DatabaseConnection=Server=taskplanner_db; Database=TaskPlannerDb; User Id=sa; Password=@sqlserver2023; TrustServerCertificate=True"
    depends_on:
      - taskplanner_db
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro