version: '3.4'

services:
  taskplanner_db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  taskplanner:
    image: ${DOCKER_REGISTRY-}taskplanner
    build:
      context: .
      dockerfile: TaskPlanner/Dockerfile

